require("guess-indent").setup({})
require("todo-comments").setup({ signs = false })

require("config.plugins.utils")
require("config.plugins.which_key")
require("config.plugins.gitsigns")
require("config.plugins.lsp")
require("config.plugins.mini_nvim")
require("config.plugins.noice")
require("config.plugins.chezmoi")
require("config.plugins.statusline")
require("config.plugins.telescope")
require("config.plugins.nvim_treesitter")
require("config.plugins.spider")
require("config.plugins.autopairs")
require("config.plugins.neo-tree")
